# Operações em Matrizes Numpy

In [ ]:
import numpy as np

In [ ]:
np.arange(6, 10)

array([6, 7, 8, 9])

## Operações em uma matriz **1D**


Operadores aritiméticos com Numpy


Para esse primeiro exemplo, vamos soma duas matrizes 1D de mesmo tamanho, para que a soma possa ser realizada as matrizes devem ter mesma quantidade de itens, nesse exemplo cada matriz possue 5 elementos

mas posições correspondentes de cada matriz se soma

In [ ]:
# Matriz 1D com 5 elementos
matriz1 = np.arange(6, 11) 

# Matriz 1D com 5 elementos
matriz2 = np.array([1, 2, 3, 4, 5])

# Soma entre os elementos das matrizes: matriz1 + Matriz2
matriz3 = matriz1 + matriz2

# Subtração entre os elementos das matrizes: matriz1 + Matriz2
matriz4 = matriz1 - matriz2

# Multiplicação entre os elementos das matrizes: matriz1 + Matriz2
matriz5 = matriz1 * matriz2

# Divição entre os elementos das matrizes: matriz1 + Matriz2
matriz6 = matriz1 / matriz2

print(f"Matriz1 : {matriz1}")
print(f"Matriz2 : {matriz2}")
print()
print(f"matriz1 + matriz2: {matriz3}")
print(f"matriz1 - matriz2: {matriz4}")
print(f"matriz1 * matriz2: {matriz5}")
print(f"matriz1 / matriz2: {matriz6}")


Matriz1 : [ 6  7  8  9 10]
Matriz2 : [1 2 3 4 5]

matriz1 + matriz2: [ 7  9 11 13 15]
matriz1 - matriz2: [5 5 5 5 5]
matriz1 * matriz2: [ 6 14 24 36 50]
matriz1 / matriz2: [6.         3.5        2.66666667 2.25       2.        ]



Caso você tentar somar matrizes de mesma dimensão, mas com quantidades de elementos diferentes ocorrerar um erro

In [ ]:
matriz7 = np.array([1, 2, 3, 4])

matriz1 + matriz7

ValueError: ignored

## Operações aritiméticas em matrizes por um Escalar

É possível aplicar um operador aritimético na matriz com um Escalar, todos os elementos da matriz irá sofrer a ação desse operador individualmente

In [ ]:
m8 = np.array([1, 2, 3, 4, 5])

print(f"Matriz m8: {m8}")

print()

# Somando a matriz com um escalar
print(f"m8 + 2:  {m8 + 2}")

# Subtração de matriz com um escalar
print(f"m8 - 2:  {m8 - 2}")

# Multiplicando por Escalar
print(f"m8 * 2:  {m8 * 2}")

# Divisão de matriz por um Escalar
print(f"m8 / 2:  {m8 / 2}")

# elevando a matriz a uma potência
print(f"m8 ** 2: {m8 ** 2}")



Matriz m8: [1 2 3 4 5]

m8 + 2:  [3 4 5 6 7]
m8 - 2:  [-1  0  1  2  3]
m8 * 2:  [ 2  4  6  8 10]
m8 / 2:  [0.5 1.  1.5 2.  2.5]
m8 ** 2: [ 1  4  9 16 25]


## Usando Numpy com Expressões Condicionais

Podemos usar expressões condicionais para retorna valores booleanos nas posições dos elementos da matriz


In [ ]:
matriz6 = np.array([7, -3, 4, 2, 7, 3, 8, 9, 1])
print(matriz6)

# Aplicando expressões condicionais ma matriz6 
m7 = matriz6 > 5
print(m7)

[ 7 -3  4  2  7  3  8  9  1]
[ True False False False  True False  True  True False]


In [ ]:
# Além disso, podemos pegar os elementos das posições True da matriz usando o seguinte código
matriz6[m7]

array([7, 7, 8, 9])

In [ ]:
# Outra forma de obter o mesmo resultado anterior é a seguinte sintax
matriz6[matriz6 > 5]

array([7, 7, 8, 9])

# Operações em Matrizes 2D


In [ ]:
M1 = np.array([[1,2],[3,4]])
M2 = np.array([[1,2],[3,4]])

In [ ]:
M1

array([[1, 2],
       [3, 4]])

In [ ]:
M2

array([[1, 2],
       [3, 4]])

In [ ]:
M1 + M2

array([[2, 4],
       [6, 8]])

In [ ]:
M1 - M2

array([[0, 0],
       [0, 0]])

In [ ]:
M1 * M2

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
M1 / M2

array([[1., 1.],
       [1., 1.]])

# Produto de matrizes 
você pode usar o operador ‘@.’

Em matemática, o produto de duas matrizes é definido somente quando o número de colunas da primeira matriz é igual ao número de linhas da segunda matriz. Se A é uma matriz m×n e B é uma matriz n×p, então seu produto é uma matriz m×p definida como AB.
https://pt.wikipedia.org/wiki/Produto_de_matrizes


### Forma 1

In [ ]:
M1 = np.array([[1,2],[3,4]])
M2 = np.array([[1,2],[3,4]])

M1 @ M2

array([[ 7, 10],
       [15, 22]])

### Forma 2

In [ ]:
M1.dot(M2)

array([[ 7, 10],
       [15, 22]])

# Funções aritméticas em Matrizes Numpy


In [ ]:
matriz9 = np.array([1, 2, 3, 4, 5])

In [ ]:
# Soma dos elementos da matriz
matriz9.sum()

15

#### A função min encontra o valor mais baixo na matriz.


In [ ]:
matriz9.min()

1

### O Maior elemento da Matriz

In [ ]:
matriz9.max()

5

### Média dos valores da Matriz

In [ ]:
matriz9.mean()

3.0

### Retorna o desvio padrão dos elementos da matriz ao longo do eixo fornecido.


In [ ]:
matriz9.std()

1.4142135623730951

# Operadores aplicados aos eixos das matrizes

Matrizes são formadas por eixos, uma matriz unidimencional possue 1 eixo, já uma matriz bi-dimencional possue 2 eixos e assim sucessivamente.
vamos aplicar alguns parâmentros para trabalhar com os valores de uma matriz e fazer algumas operações aritiméticas 

In [ ]:
# Criando uma matriz Bidimencional
matriz10 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
matriz10

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

### Acessando os valores da coluna 1 dessa matriz

In [ ]:
matriz10[:, 1]

array([2, 2])

### Acessando os valores da linha 1 dessa matriz

In [ ]:
matriz10[1, :]

array([1, 2, 3, 4])

# Execultando Operações Aritiméticas nos Eixos de uma Matriz

### Operadores Aritiméticas aplicado nas colunas de Uma *matriz*

In [ ]:
# Soma dos elementos da columa 2 da matriz10
s_elemento_c2 = matriz10[:, 2].sum()

# Multiplicação dos elementos da coluna 2 da Matriz10
m_elemento_c2 = matriz10[:, 2].prod()

# Print dos valores
print(f"Soma Elementos Coluna 1: {s_elemento_c2}")
print(f"Multiploicação Elementos Coluna 1: {m_elemento_c2}")


Soma Elementos Coluna 1: 6
Multiploicação Elementos Coluna 1: 9


Operações Aritiméticas nas linhas de Uma matriz

In [ ]:
# Soma dos elementos da linha 1 da matriz10
s_elemento_l1 = matriz10[1, :].sum()

# Multiplicação dos elementos da linha 1 da Matriz10
m_elemento_l1 = matriz10[1, :].prod()

# Print dos valores
print(f"Soma Elementos Linha 1: {s_elemento_l1}")
print(f"Multiploicação Elementos Linha 1: {m_elemento_l1}")

Soma Elementos Linha 1: 10
Multiploicação Elementos Linha 1: 24


# Soma de cada coluna de uma Matriz

In [ ]:
matriz10.sum(axis = 0)

array([2, 4, 6, 8])

### Soma dos elementos das linhas de uma matriz

In [ ]:
matriz10.sum(axis = 1)

array([10, 10])

# Operadores lógicos em Numpy


### Operador AND 

In [ ]:
# Esse método é usado para comparar valores Booleanos AND 
np.logical_and(True, True)


True

In [ ]:
# Esse método é usado para comparar valores Booleanos AND 
np.logical_and(False, True)

False

### Operador OR

In [ ]:
np.logical_or(7>6,0>1)


True

In [ ]:
# Esse método é usado para comparar valores Booleanos OR
np.logical_or(2>6,0>1)


False

### Operador NOT

In [ ]:
np.logical_not(False)

True

In [ ]:
np.logical_not(True)

False

### Operador XOR

In [ ]:
np.logical_xor(True, False)

True

In [ ]:
np.logical_xor([True, True, False, False], [True, False, True, False])

array([False,  True,  True, False])

# Operações Aritméticas

### Soma de matrizes

In [ ]:
matriz11 = np.arange(9).reshape(3,3)
matriz11

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
matriz12 = np.array([1, 2, 3])
matriz12

array([1, 2, 3])

In [ ]:
add_matriz = np.add(matriz11, matriz12)
add_matriz

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

### Subtração de elementos de matrizes

In [ ]:
sub_matriz = np.subtract(matriz11, matriz12)
sub_matriz

array([[-1, -1, -1],
       [ 2,  2,  2],
       [ 5,  5,  5]])

### Multiplicação de elementos entre matrizes

In [ ]:
mult_matriz = np.multiply(matriz11, matriz12)
mult_matriz

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

### Divisão de elementos entre matrizes

In [ ]:
div_matriz = np.divide(matriz11, matriz12)
div_matriz

array([[0.        , 0.5       , 0.66666667],
       [3.        , 2.        , 1.66666667],
       [6.        , 3.5       , 2.66666667]])