# Tipos de Inicializações de Matrizes usando Numpy



In [ ]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

O Método array da Biblioteca Numpy nos forcesse a possibilidade de criar matrizes de n-dimensões.

Nesse exemplo vamos criar uma matriz 2D com 2 Linhas e 3 Colunas

In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

ao criarmos a matriz assim, podemos obter algumas caracteristicas dessa matrix, que chamamos em python de atribultos

Os atributos mais importantes de um objeto ndarray são:


ndarray.ndim : o número de eixos (dimensões) da matriz.

In [ ]:
matriz.ndim

2

ndarray.shape: as dimensões da matriz

In [ ]:
matriz.shape

(2, 3)

ndarray.size: o número total de elementos da matriz.

In [ ]:
matriz.size

6

ndarray.dtype: um objeto que descreve o tipo dos elementos na matriz.

In [ ]:
matriz.dtype

dtype('int64')

ndarray.itemsize: o tamanho em bytes de cada elemento da matriz

Por exemplo, uma matriz de elementos do tipo float64 tem o tamanho de item 8 (= 64/8).

In [ ]:
matriz.itemsize

8

o buffer que contém os elementos reais da matriz. Normalmente, não precisaremos usar este atributo porque acessaremos os elementos em uma matriz usando recursos de indexação.


In [ ]:
matriz.data

In [ ]:
print(f"Dimensão da matriz: {matriz.ndim}")
print(f"Shape da Matriz: {matriz.shape}")
print(f"Número de elementos da Matriz: {matriz.size}")
print(f"Tipo dos elementos da Matriz: {matriz.dtype}")
print(f"Tamanho em Bytes de cada elemento da Matriz: {matriz.itemsize}")
print(f"Local da menmória onde está alocado essa matriz: {matriz.data}")

# Inicialização de Matrizes
Podemos inicializar matrizes de diferentes formas, vamos ver algumas delas

### numpy.arange

Retorna valores com espaçamento uniforme dentro de um determinado intervalo.

<code> numpy.arange(start, stop, step, dtype=None, *, like=None) </code>

- Parameters

  - start : integer or real, optional

    Início do intervalo. O intervalo inclui esse valor. O valor inicial padrão é 0.

  - stop : integer or real

    Fim do intervalo. O intervalo não inclui esse valor, exceto em alguns casos em que a etapa não é um número inteiro e o arredondamento de ponto flutuante afeta o comprimento de fora.

  - step : integer or real, optional

    Espaçamento entre valores.


In [ ]:
matriz2 = np.arange(1,12,2)
matriz2

array([ 1,  3,  5,  7,  9, 11])

ainda com o arange podemos usar o método reshape para modificar o shape da matriz

In [ ]:
matriz2 = matriz2.reshape(2, 3)
matriz2

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [ ]:
type(matriz)

numpy.ndarray

### numpy.zeros
Esse método da biblioteca Numpy possibilita a inicialização de matrizes de n-dimensões com valores 0.

<code> numpy.zeros(shape, dtype=float, order='C') </code>

- Parâmetros

  - shape

    é a formato da matriz
  - dtype
  
    Dtype: é o tipo de dados em zeros numpy. É opcional. O valor padrão é float64
  - order

    é um estilo de linha essencial para numpy.ones () em Python.


Obs: todas essas inicializações por ser um objeto numpy tem dodos os atrbultos descritos nas etapas anteriores, como: ndarray.ndim, ndarray.shape, ndarray.size, ndarray.dtype etc.

In [ ]:
matriz_zeros = np.zeros((3, 3))
matriz_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
matriz_zeros.dtype

dtype('float64')

### numpy.ones
Esse método possibilita a inicialização de matrizes de n-dimensões com valores 1.

<code> numpy.ones(shape, dtype=float, order='C') </code>


Obs: Possue os mesmos atribultos do método numpy.zeros

In [ ]:
matriz_uns = np.ones((2, 3, 3), dtype = "int64", order = "C")
matriz_uns

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [ ]:
matriz_uns.dtype

dtype('int64')

### numpy.empty

Esse método é usada para criar uma matriz sem inicializar, os valores mostrados são chamados de lixo de memória, ou seja, são valores que já estavam na menmória antes de criar a matriz, esse método é conveniente quando se quer criar matrizes rapidamente, pois ela tem uma maior perfomasse para serem criadas.

<code> numpy.empty(shape, dtype=float, order='C') </code>


In [ ]:
matriz_empty = np.empty((2, 3, 2), dtype = "float64", order = "C")
matriz_empty

array([[[4.64676688e-310, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.58817677e-052]],

       [[5.27966871e-091, 4.74968792e+174],
        [5.54476431e+169, 8.23035692e-067],
        [3.99910963e+252, 1.46030983e-319]]])

In [ ]:
matriz_empty.shape

(2, 3, 2)

### numpy.linspace

<code> numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) </code>

- Parâmetros

  - start

    O valor inicial da sequência.
  - stop
  
    O valor final da sequência
  - num

    Número de amostras a serem geradas. O padrão é 50. Não deve ser negativo.

  - endpoint

    Se for True, stop é a última amostra. Caso contrário, não está incluído. O padrão é True.

  - retstep

    Se for True, retorna (samples, step), onde step é o espaçamento entre as amostras.

  - dtype

    O tipo da matriz de saída.

  - axis

    O eixo no resultado para armazenar as amostras. Relevante apenas se start ou stop forem semelhantes a array. Por padrão (0), as amostras estarão ao longo de um novo eixo inserido no início. Use -1 para obter um eixo no final.

  - Returns

    Existem núm amostras igualmente espaçadas no intervalo fechado [iniciar, parar] ou no intervalo semi-aberto [iniciar, parar) (dependendo se o ponto final é Verdadeiro ou Falso).

  - step

    Retornado apenas se retstep for True Tamanho do espaçamento entre as amostras.


In [ ]:
matriz_linspace = np.linspace(0, 10, num=20, dtype = "float64")
matriz_linspace

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])